// Generated by CoffeeScript 1.7.1
var domain, serverurl;

serverurl = 'http://localhost:8008/apikey/open/';

domain = 'metoceanview.com';

wxtiles.loadConfiguration(serverurl, domain, function(config) {
  var map, nzapstrike, randomindex, wxTilesLayer;
  wxTilesLayer = L.wxTileLayer(config, {
    maxZoom: 7,
    maxNativeZoom: 8,
    reuseTiles: true
  });
  randomindex = Math.floor(Math.random() * config.fields.length);
  wxTilesLayer.setField(config.fields[randomindex]);
  nzapstrike = L.tileLayer('http://map{s}.nzapstrike.net/aqua3/{z}/{x}/{y}.png', {
    maxZoom: 8,
    reuseTiles: true
  });
  map = new L.Map('map', {
    layers: [nzapstrike, wxTilesLayer],
    center: new L.LatLng(-37.7772, 175.2756),
    zoom: 6,
    attributionControl: false
  });
  return setTimeout(function() {
    return wxTilesLayer.forward();
  }, 10000);
});
