// Generated by CoffeeScript 1.7.1
var domain, serverurl;

serverurl = 'http://localhost:8008/apikey/open/';

domain = 'metoceanview.com';

wxtiles.loadConfiguration(serverurl, domain, function(config) {
  var exampleLayer, field, key, map, nzapstrike, randomindex, _i, _j, _len, _len1, _ref, _ref1;
  console.log('KEYS');
  _ref = config.keys;
  for (_i = 0, _len = _ref.length; _i < _len; _i++) {
    key = _ref[_i];
    console.log("" + key.name + ": " + key.description);
  }
  console.log('FIELDS');
  _ref1 = config.fields;
  for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
    field = _ref1[_j];
    console.log("" + field.name + ": " + field.description);
  }
  randomindex = Math.floor(Math.random() * config.fields.length);
  field = config.fields[randomindex];
  key = config.keys[Math.round(config.keys.length / 2)];
  console.log("DISPLAYING " + field.description + " @ " + key.description);
  exampleLayer = L.tileLayer("" + serverurl + "tile/" + config.cycle + "/" + field.name + "/" + key.name + "/{z}/{x}/{y}.png", {
    opacity: field.defaultalpha,
    maxZoom: 14,
    tms: true,
    reuseTiles: true
  });
  nzapstrike = L.tileLayer('http://map{s}.nzapstrike.net/aqua3/{z}/{x}/{y}.png', {
    maxZoom: 8,
    reuseTiles: true
  });
  return map = new L.Map('map', {
    layers: [nzapstrike, exampleLayer],
    center: new L.LatLng(-37.7772, 175.2756),
    zoom: 7
  });
});
